language: node_js
node_js:
- "8.2.1"

services:
- docker

before_install:
- docker-compose build && docker-compose up -d

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- chmod 777 Ci/script/WaitServer.sh
- ./Ci/script/WaitServer.sh
- node_modules/.bin/newman run Ci/tests/TEST.postman_collection.json -e Ci/tests/JSONBlob.postman_environment.json
- node_modules/.bin/newman run Ci/tests/testApiNeoconnect.postman_collection.json
